config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  resources :users
  resources :tweets do
    member do
      post "favorite"
    end
  end


  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to user_path(user)
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    WitterService.new(current_user).create_tweet(params["Tweet"]["tweet"])
    sleep(2)
    redirect_to :back
  end

  def favorite
    binding.pry
    WitterService.new(current_user).favorite(params["id"].to_i)
    sleep(2)
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @service = WitterService.new(current_user)
    @tweet = "Tweet"
  end

  def show
    @service = WitterService.new(current_user)
    @tweet = "Tweet"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Witter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center"><img src="http://danbubanygolf.com/wp-content/uploads/2015/09/Twitter-icon.png", height= "60px", width="60px"></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li> <%= link_to "Home", users_path %></a></li>
          <li><% if @service %>
        <%= link_to "Logout", logout_path %>
        <% else %>
        <%= link_to "Login", login_path %>
        <% end %></li>
    </ul>
    </div>
  </nav>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class="container">
  <h4 class="amber-text">Homefeed</h4>
</div>
<div class="row">
  <div class="col s3">
    <div class="card">
      <img src="http://pbs.twimg.com/profile_images/646725390044557312/QakSSAhz_normal.jpg">
        <span class="card-title"><%= @service.user.name %></span>
      <div class="card-content">
        <p>@<%= @service.user.screen_name %></p>
      <div class="card-action">
        <div class="col s4">
          <p>tweets: <%= @service.tweets.count %></p>
        </div>
        <div class="col s4">
          <p>followers: <%= @service.client.followers.count %></p>
        </div>
        <div class="col s4">
          <p>following: <%= @service.client.friends.count %></p>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="col s9">
    <div class="card">
      <% @service.home_timeline.each do |tweet| %>
        <div class="card" style="border-solid">
          <div class="row" style="margin-left:6px; margin-top:6px; margin-right:6px">
            <p>
            <div class="avatar col s1"><img src="<%= tweet.user.profile_image_url %>"></div>
            <div class="col s10">
              <%= tweet.user.screen_name %>
              <%= tweet.text %>
              <% if tweet.favorited? %>
                <div class="red-text"> <3 </div>
              <%  else %>
                <%= link_to "Favorite", favorite_tweet_path(tweet.id), method: :post %>
              <% end %>
            </div>
          </div>
        </div>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h4 class="amber-text">My Tweets</h4>
</div>
<div class="row">
  <div class="col s3">
    <div class="card">
      <img src="http://pbs.twimg.com/profile_images/646725390044557312/QakSSAhz_normal.jpg">
        <span class="card-title"><%= @service.user.name %></span>
      <div class="card-content">
        <p>@<%= @service.user.screen_name %></p>
      <div class="card-action">
        <div class="col s4">
          <p>tweets: <%= @service.tweets.count %></p>
        </div>
        <div class="col s4">
          <p>followers: <%= @service.client.followers.count %></p>
        </div>
        <div class="col s4">
          <p>following: <%= @service.client.friends.count %></p>
        </div>
      </div>
    </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="card">
    <%= form_for(@tweet, url: tweets_path) do |f| %>
      <%= f.label :tweet %>
      <%= f.text_field :tweet %>
      <div class="button"><%= f.submit "New Tweet" %></div>
    <% end %>
  </div>
  </div>
  <div class="col s9">
    <div class="card">
      <% @service.user_timeline.each do |tweet| %>
        <div class="card" style="border-solid">
          <div class="row" style="margin-left:6px; margin-top:6px; margin-right:6px">
            <p>
            <div class="avatar col s1"><img src="<%= tweet.user.profile_image_url %>"></div>
            <div class="col s10">
              <%= tweet.user.screen_name %>
              <%= tweet.text %>
              <% if tweet.favorited? %>
                <div class="red-text"> <3 </div>
                <3
              <%  else %>
                <%= link_to "Favorite", favorite_tweet_path(tweet.id), method: :post %>
              <% end %>
            </div>
          </div>
        </div>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <h1 class="center">Welcome to Witter!</h1>
  <h5 class="center">Feel confident in bypassing all rants, naysayers, and all around angry people with this Twitter spinoff.  Here at WItter we believe in for lack of a better word, witty and uplifting messages.  Come here for inspiration, a pick me up, or simply a break with your morning coffee. We take pride in getting your day started off the "Witter" way.</h5>
  <h3 class="center">Cheers.</h3>
<br><br><br><br>
  <div class="row">
    <div class="col s4">
      <div class="card">
        <div class="card-image">
          <img src="https://usatthebiglead.files.wordpress.com/2012/12/cam-newton-panthers-qb1.jpg">
          <span class="card-title">Panthers Nation</span>
        </div>
        <div class="card-content">
          <p>Trending Now: Panthers are undefeated and looking like Super Bowl favorites.</p>
        </div>
        <div class="card-action">
          <a href="https://twitter.com/Panthers">#panthers</a>
        </div>
      </div>
    </div>


    <div class="col s4">
      <div class="card">
        <div class="card-image">
          <img src="http://dailyroabox.com/wp-content/uploads/2015/10/The-Grand-Old-Party-us-election.jpg">
          <span class="card-title">Election 2016</span>
        </div>
        <div class="card-content">
          <p>Trending Now: The pressure is on with the candidates in Election 2016.</p>
        </div>
        <div class="card-action">
          <a href="https://twitter.com/i/moments/676885448279502848">#election2016</a>
        </div>
      </div>
    </div>


    <div class="col s4">
      <div class="card">
        <div class="card-image">
          <img src="http://cdn.citylab.com/media/img/citylab/2014/12/sydney_storm_severe_weather_stormchasing_pictures_photos_video_friday_december_5_2014_2/lead_large.jpg">
          <span class="card-title">Winter Weather</span>
        </div>
        <div class="card-content">
          <p>Trending Now: The hail is hitting Sydney and it is hittig it hard!</p>
        </div>
        <div class="card-action">
          <a href="https://twitter.com/hashtag/sydneystorm?src=tren">#sydneystorm</a>
        </div>
      </div>
    </div>
  </div>
</div>